/*
 * This file is generated by jOOQ.
 */
package com.prj.quiz.persistence.jooq;


import com.prj.quiz.persistence.jooq.tables.Content;
import com.prj.quiz.persistence.jooq.tables.Theme;
import com.prj.quiz.persistence.jooq.tables.User;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CONTENT_CONTENT_FK_THEME = Indexes0.CONTENT_CONTENT_FK_THEME;
    public static final Index CONTENT_PRIMARY = Indexes0.CONTENT_PRIMARY;
    public static final Index THEME_PRIMARY = Indexes0.THEME_PRIMARY;
    public static final Index USER_PRIMARY = Indexes0.USER_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CONTENT_CONTENT_FK_THEME = Internal.createIndex("content_fk_theme", Content.CONTENT, new OrderField[] { Content.CONTENT.THEME_ID }, false);
        public static Index CONTENT_PRIMARY = Internal.createIndex("PRIMARY", Content.CONTENT, new OrderField[] { Content.CONTENT.ID }, true);
        public static Index THEME_PRIMARY = Internal.createIndex("PRIMARY", Theme.THEME, new OrderField[] { Theme.THEME.ID }, true);
        public static Index USER_PRIMARY = Internal.createIndex("PRIMARY", User.USER, new OrderField[] { User.USER.ID }, true);
    }
}
