/*
 * This file is generated by jOOQ.
 */
package com.prj.quiz.persistence.jooq.tables.records;


import com.prj.quiz.persistence.jooq.tables.Study;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudyRecord extends UpdatableRecordImpl<StudyRecord> implements Record5<Integer, String, String, Integer, Integer> {

    private static final long serialVersionUID = -994854676;

    /**
     * Setter for <code>study.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>study.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>study.word</code>.
     */
    public void setWord(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>study.word</code>.
     */
    public String getWord() {
        return (String) get(1);
    }

    /**
     * Setter for <code>study.translation</code>.
     */
    public void setTranslation(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>study.translation</code>.
     */
    public String getTranslation() {
        return (String) get(2);
    }

    /**
     * Setter for <code>study.content_id</code>.
     */
    public void setContentId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>study.content_id</code>.
     */
    public Integer getContentId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>study.level_id</code>.
     */
    public void setLevelId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>study.level_id</code>.
     */
    public Integer getLevelId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Study.STUDY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Study.STUDY.WORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Study.STUDY.TRANSLATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Study.STUDY.CONTENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Study.STUDY.LEVEL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getWord();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTranslation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getContentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getLevelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getWord();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTranslation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getContentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getLevelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudyRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudyRecord value2(String value) {
        setWord(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudyRecord value3(String value) {
        setTranslation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudyRecord value4(Integer value) {
        setContentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudyRecord value5(Integer value) {
        setLevelId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudyRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StudyRecord
     */
    public StudyRecord() {
        super(Study.STUDY);
    }

    /**
     * Create a detached, initialised StudyRecord
     */
    public StudyRecord(Integer id, String word, String translation, Integer contentId, Integer levelId) {
        super(Study.STUDY);

        set(0, id);
        set(1, word);
        set(2, translation);
        set(3, contentId);
        set(4, levelId);
    }
}
